import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './Provider'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <Providers>
        <div className='w-full bg-gray-800 min-h-screen h-auto  max-w-screen-2xl mx-auto flex relative flex-col'>
          <Navbar/>

        {children}
        </div>
        </Providers>
        </body>
    </html>
  )
}
